### ISSUE TITLE
ACL bug

### ISSUE THREAD

**Issue by scriptum** [MrHalabaluza/mephi-BOS#1]
Не воспринимает корректный ввод при добавлении ACL прав доступа.

![acl-bug](https://cloud.githubusercontent.com/assets/695971/20879763/a8acdd0e-baee-11e6-8983-f7c527011376.png)

**Comment by scriptum** [comment]
Ошибка исправлена?

**Comment by AlinaGarbuz** [comment]
Да, указанная ошибка была исправлена!
